_wandb:
    value:
        cli_version: 0.24.2
        e:
            21tqne4joekrphgw8520bu0vf1l8wtiz:
                args:
                    - --dataset_name
                    - privasis
                    - --enc_dec_model
                    - facebook/bart-base
                    - --train_batch_size
                    - "16"
                    - --eval_batch_size
                    - "16"
                    - --num_encoder_latents
                    - "32"
                    - --num_decoder_latents
                    - "32"
                    - --dim_ae
                    - "256"
                    - --num_layers
                    - "2"
                    - --learning_rate
                    - "5e-5"
                    - --num_train_steps
                    - "100000"
                    - --eval_every
                    - "1000"
                    - --max_val_batches
                    - "50"
                    - --wandb_name
                    - baseline_privasis_autoencoder_eval
                    - --output_dir
                    - saved_latent_models_outputs/baseline_privasis_ae
                    - --save_dir
                    - saved_latent_models/privasis_autoencoder
                    - --resume_dir
                    - saved_latent_models_outputs/baseline_privasis_ae
                    - --eval
                codePath: train_latent_model.py
                codePathLocal: train_latent_model.py
                cpu_count: 112
                cpu_count_logical: 112
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "470822744064"
                        used: "34650431488"
                email: prakritishetty02@gmail.com
                executable: /home/psshetty_umass_edu/.conda/envs/latent-lang-diff/bin/python
                git:
                    commit: f653342261154e13c6890c9f8d8413d2f8958804
                    remote: https://github.com/prakritishetty/Diffusion_as_Memory.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-9b56f531-9a59-b0b3-91ff-c9790c32a51f
                host: gpu022
                memory:
                    total: "2163942625280"
                os: Linux-6.8.0-94-generic-x86_64-with-glibc2.17
                program: train_latent_model.py
                python: CPython 3.8.13
                root: saved_latent_models_outputs/baseline_privasis_ae
                slurm:
                    cluster_name: unity
                    conf: /var/spool/slurm/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "1"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: pi_hzamani_umass_edu
                    job_cpus_per_node: "1"
                    job_end_time: "1777334099"
                    job_gid: "4005"
                    job_gpus: "6"
                    job_id: "56390300"
                    job_name: interactive
                    job_nodelist: gpu022
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: short
                    job_start_time: "1777319699"
                    job_uid: "4005"
                    job_user: psshetty_umass_edu
                    jobid: "56390300"
                    launch_node_ipaddr: 10.100.1.1
                    localid: "0"
                    mem_per_node: "51200"
                    mpi_type: pmi2
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu022
                    oom_kill_step: "0"
                    pmi2_proc_mapping: (vector,(0,1,1))
                    pmi2_srun_port: "19143"
                    pmi2_step_nodes: gpu022
                    prio_process: "0"
                    procid: "0"
                    pty_port: "10571"
                    pty_win_col: "132"
                    pty_win_row: "13"
                    script_context: prolog_task
                    srun_comm_host: 10.100.1.1
                    srun_comm_port: "27387"
                    step_id: "4294967290"
                    step_launcher_port: "27387"
                    step_nodelist: gpu022
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    stepmgr: gpu022
                    submit_dir: /gypsum/work1/zamani/prakriti/privasis_baseline
                    submit_host: login1
                    task_pid: "3918755"
                    tasks_per_node: "1"
                    topology_addr: ..tors-r1pac17.gpu022
                    topology_addr_pattern: switch.switch.switch.node
                startedAt: "2026-04-27T19:57:45.993668Z"
                writerId: 21tqne4joekrphgw8520bu0vf1l8wtiz
        m: []
        python_version: 3.8.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 33
                - 41
                - 49
                - 51
                - 53
                - 71
                - 75
                - 100
            "2":
                - 1
                - 5
                - 11
                - 33
                - 41
                - 49
                - 51
                - 53
                - 71
                - 75
                - 100
            "3":
                - 13
                - 61
            "4": 3.8.13
            "5": 0.24.2
            "6": 4.46.3
            "12": 0.24.2
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_weight_decay:
    value: 0.01
dataset_name:
    value: privasis
dim_ae:
    value: 256
enc_dec_model:
    value: facebook/bart-base
eval:
    value: true
eval_batch_size:
    value: 16
eval_every:
    value: 1000
l2_normalize_latents:
    value: false
learning_rate:
    value: 5e-05
lm_mode:
    value: freeze
lr_schedule:
    value: linear
lr_warmup_steps:
    value: 500
max_seq_len:
    value: 64
max_train_samples:
    value: 50000
max_val_batches:
    value: null
mixed_precision:
    value: "no"
no_validation:
    value: true
num_decoder_latents:
    value: 32
num_devices:
    value: 1
num_encoder_latents:
    value: 32
num_layers:
    value: 2
num_train_steps:
    value: 100000
optimizer:
    value: adamw
output_dir:
    value: saved_latent_models_outputs/baseline_privasis_ae
resume_dir:
    value: saved_latent_models_outputs/baseline_privasis_ae
resume_training:
    value: false
save_dir:
    value: saved_latent_models/privasis_autoencoder
save_every:
    value: 5000
train_batch_size:
    value: 16
wandb_name:
    value: baseline_privasis_autoencoder_eval
