_wandb:
    value:
        cli_version: 0.24.2
        e:
            qyo9c3huoeg3thr7wrivflh1d0m2q526:
                args:
                    - --dataset_name
                    - privasis
                    - --enc_dec_model
                    - facebook/bart-base
                    - --latent_model_path
                    - saved_latent_models_outputs/baseline_privasis_ae
                    - --tx_dim
                    - "512"
                    - --tx_depth
                    - "6"
                    - --train_batch_size
                    - "16"
                    - --eval_batch_size
                    - "16"
                    - --num_train_steps
                    - "100000"
                    - --learning_rate
                    - "1e-4"
                    - --wandb_name
                    - baseline_privasis_diffusion
                    - --output_dir
                    - saved_diffusion_outputs/baseline_privasis_diff
                    - --save_dir
                    - saved_diff_models/baseline_privasis_diff
                    - --objective
                    - pred_v
                    - --loss_type
                    - l2
                codePath: train_text_diffusion.py
                codePathLocal: train_text_diffusion.py
                cpu_count: 112
                cpu_count_logical: 112
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "470822744064"
                        used: "54709690368"
                email: prakritishetty02@gmail.com
                executable: /home/psshetty_umass_edu/.conda/envs/latent-lang-diff/bin/python
                git:
                    commit: f653342261154e13c6890c9f8d8413d2f8958804
                    remote: https://github.com/prakritishetty/Diffusion_as_Memory.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-9b56f531-9a59-b0b3-91ff-c9790c32a51f
                host: gpu022
                memory:
                    total: "2163942625280"
                os: Linux-6.8.0-94-generic-x86_64-with-glibc2.17
                program: train_text_diffusion.py
                python: CPython 3.8.13
                root: saved_diffusion_outputs/baseline_privasis_diff
                slurm:
                    cluster_name: unity
                    conf: /var/spool/slurm/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "1"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: pi_hzamani_umass_edu
                    job_cpus_per_node: "1"
                    job_end_time: "1777334099"
                    job_gid: "4005"
                    job_gpus: "6"
                    job_id: "56390300"
                    job_name: interactive
                    job_nodelist: gpu022
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: short
                    job_start_time: "1777319699"
                    job_uid: "4005"
                    job_user: psshetty_umass_edu
                    jobid: "56390300"
                    launch_node_ipaddr: 10.100.1.1
                    localid: "0"
                    mem_per_node: "51200"
                    mpi_type: pmi2
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu022
                    oom_kill_step: "0"
                    pmi2_proc_mapping: (vector,(0,1,1))
                    pmi2_srun_port: "19143"
                    pmi2_step_nodes: gpu022
                    prio_process: "0"
                    procid: "0"
                    pty_port: "10571"
                    pty_win_col: "132"
                    pty_win_row: "13"
                    script_context: prolog_task
                    srun_comm_host: 10.100.1.1
                    srun_comm_port: "27387"
                    step_id: "4294967290"
                    step_launcher_port: "27387"
                    step_nodelist: gpu022
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    stepmgr: gpu022
                    submit_dir: /gypsum/work1/zamani/prakriti/privasis_baseline
                    submit_host: login1
                    task_pid: "3918755"
                    tasks_per_node: "1"
                    topology_addr: ..tors-r1pac17.gpu022
                    topology_addr_pattern: switch.switch.switch.node
                startedAt: "2026-04-27T20:43:49.658901Z"
                writerId: qyo9c3huoeg3thr7wrivflh1d0m2q526
        m: []
        python_version: 3.8.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 33
                - 41
                - 49
                - 51
                - 53
                - 71
                - 75
                - 100
            "2":
                - 1
                - 5
                - 11
                - 33
                - 41
                - 49
                - 51
                - 53
                - 71
                - 75
                - 100
            "3":
                - 13
            "4": 3.8.13
            "5": 0.24.2
            "6": 4.46.3
            "12": 0.24.2
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_weight_decay:
    value: 1e-06
amp:
    value: false
class_conditional:
    value: false
class_unconditional_prob:
    value: 0.1
clip_grad_norm:
    value: 1
dataset_name:
    value: privasis
disable_dropout:
    value: false
ema_decay:
    value: 0.9999
ema_update_every:
    value: 1
enc_dec_model:
    value: facebook/bart-base
eval:
    value: false
eval_batch_size:
    value: 16
eval_test:
    value: false
gradient_accumulation_steps:
    value: 1
init_path:
    value: null
latent_model_path:
    value: saved_latent_models_outputs/baseline_privasis_ae
learning_rate:
    value: 0.0001
loss_type:
    value: l2
lr_schedule:
    value: cosine
lr_warmup_steps:
    value: 1000
max_seq_len:
    value: 64
mixed_precision:
    value: "no"
normalize_latent:
    value: false
num_dense_connections:
    value: 0
num_devices:
    value: 1
num_samples:
    value: 16
num_train_steps:
    value: 100000
objective:
    value: pred_v
optimizer:
    value: adamw
output_dir:
    value: saved_diffusion_outputs/baseline_privasis_diff
resume_dir:
    value: null
resume_training:
    value: false
sampler:
    value: ddpm
sampling_schedule:
    value: null
sampling_timesteps:
    value: 250
save_and_sample_every:
    value: 5000
save_dir:
    value: saved_diff_models/baseline_privasis_diff
scale:
    value: 1
scale_shift:
    value: false
self_condition:
    value: false
seq2seq_candidates:
    value: 5
seq2seq_unconditional_prob:
    value: 0.1
train_batch_size:
    value: 16
train_prob_self_cond:
    value: 0.5
train_schedule:
    value: cosine
trainable_params:
    value: 31798528
tx_depth:
    value: 6
tx_dim:
    value: 512
wandb_name:
    value: baseline_privasis_diffusion
