_wandb:
    value:
        cli_version: 0.24.2
        e:
            24378faw7rmavlwaubbjjb1n5wnbbqys:
                codePath: dataset_utils/create_privacy_dataset.py
                codePathLocal: dataset_utils/create_privacy_dataset.py
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "34290188288"
                        used: "14636343296"
                email: prakritishetty02@gmail.com
                executable: /home/psshetty_umass_edu/.conda/envs/latent-lang-diff/bin/python
                git:
                    commit: a60da3e9c334168efd72cf534bca10af7f772fa1
                    remote: https://github.com/prakritishetty/Diffusion_as_Memory.git
                host: login1
                memory:
                    total: "135163199488"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.17
                program: dataset_utils/create_privacy_dataset.py
                python: CPython 3.8.13
                root: /gypsum/work1/zamani/prakriti/privasis_baseline
                startedAt: "2026-05-05T13:12:36.337646Z"
                writerId: 24378faw7rmavlwaubbjjb1n5wnbbqys
        m: []
        python_version: 3.8.13
        t:
            "1":
                - 1
                - 49
                - 51
                - 95
            "2":
                - 1
                - 49
                - 51
                - 95
            "3":
                - 13
            "4": 3.8.13
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
